### ISSUE TITLE
Использование javascript вместо расчетов на сервере

### ISSUE THREAD

**Issue by 0Nera** [noverd/FL#1]
Есть вероятность нехватки ресурсов сервера, советую перенести расчеты на клиентскую часть

**Comment by noverd** [comment]
Чувак... Как ты это нашел? Ну да, стоит перенести.

**Comment by 0Nera** [comment]
> Чувак... Как ты это нашел? Ну да, стоит перенести.

Я просто выбираю случайные аккаунты которые подписаны на меня и кидаю им pull-ы либо issue
Сегодня скину фикс с переносом на клиентскую часть

**Comment by 0Nera** [comment]
> Чувак... Как ты это нашел? Ну да, стоит перенести.

Оптимизировал, прошу проверить последний pull

**Comment by noverd** [comment]
> Я просто выбираю случайные аккаунты которые подписаны на меня и кидаю им pull-ы либо issue

Зачем? Ачивки gh набиваешь?

**Comment by 0Nera** [comment]
> > Я просто выбираю случайные аккаунты которые подписаны на меня и кидаю им pull-ы либо issue
> 
> Зачем? Ачивки gh набиваешь?

Практикуюсь в командной работе

**Comment by noverd** [comment]
> > > Я просто выбираю случайные аккаунты которые подписаны на меня и кидаю им pull-ы либо issue
> > 
> > 
> > Зачем? Ачивки gh набиваешь?
> 
> Практикуюсь в командной работе

Удачи тебе в этом, и да, пишется Optimization
